Fix for style to extend textfield. limitation not implemented yet.
CBIIT/bento-frontend pull request #610
Opened 2022-08-25 15:22 UTC by ogwuazors

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

2022-08-26 20:00 UTC, Nahomtes approved these changes
Issue is resolved. Textfield have enough space for 50 character.

2022-08-30 13:22 UTC, iksheth requested changes

2022-08-30 21:12 UTC, ogwuazors commented on src/bento/profileData.js
> +/**
@iksheth should be resolved now.

2022-08-31 13:00 UTC, iksheth approved these changes

2022-08-31 13:00 UTC, merged