Bento 2197 - Refactored Tab component
CBIIT/bento-frontend pull request #752
Opened 2023-03-28 19:23 UTC by Senait7-ux

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

2023-03-31 18:30 UTC, iksheth requested changes

2023-03-31 18:32 UTC, iksheth commented
@Senait7-ux Similarly like #752 Tab component is currently living in bento-core folder under bento-frontend (Bento Frontend's Reference Implementation). As we have new structure implemented. Can you migrate login component to packages folder? and import it like @bento-core/tab or @bento-core/tabs?

2023-04-03 13:31 UTC, Senait7-ux commented
Bento 2197: https://github.com/CBIIT/bento-frontend/pull/752

2023-04-04 17:41 UTC, Senait7-ux commented
> @Senait7-ux Similarly like #752 Tab component is currently living in bento-core folder under bento-frontend (Bento Frontend's Reference Implementation). As we have new structure implemented. Can you migrate login component to packages folder? and import it like @bento-core/tab or @bento-core/tabs?

https://github.com/CBIIT/bento-frontend/pull/752

2023-04-04 20:10 UTC, iksheth requested changes

2023-04-04 20:10 UTC, iksheth commented on packages/tab/src/index.js
> +import Tabs from './Tabs'
Missing ";" at the end of the line. This might fail the build while building on DEV.

2023-04-05 23:46 UTC, iksheth approved these changes

2023-04-06 01:31 UTC, iksheth commented
Merge Conflicts.

2023-04-06 02:32 UTC, iksheth commented
Merge Conflicts resolved.

2023-04-06 02:33 UTC, merged