Bento 2296 Finished login component refactoring
CBIIT/bento-frontend pull request #754
Opened 2023-03-30 14:58 UTC by Senait7-ux

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

2023-03-31 17:51 UTC, iksheth requested changes

2023-03-31 17:51 UTC, iksheth commented on packages/bento-frontend/public/injectEnv.js
> +  REACT_APP_GOOGLE_CLIENT_ID: '196014713877-0d926jpdd691roubuc0kpu6r6ha9b9t5.apps.googleusercontent.com',
Can you remove client Ids values? and replace it with 'Sample id'? We do usually do not commit client id values in github.

2023-04-03 13:30 UTC, Senait7-ux commented
Bento 2296 PR LINK : https://github.com/CBIIT/bento-frontend/pull/754

2023-04-03 16:38 UTC, iksheth requested changes

2023-04-03 16:38 UTC, iksheth commented on packages/authentication/src/data/loginProvidersData.js
@Senait7-ux This is custodian configuration file. This should be under "bento-frontend/src/bento" folder.

2023-04-03 16:38 UTC, iksheth commented on packages/authentication/src/utils/env.js
@Senait7-ux If I remember correct. This file is part of whole application. It's not part of only login functionality.

2023-04-03 16:38 UTC, iksheth commented on packages/authentication/src/utils/localStorage.js
Store to local storage is also used by Cart. This file is not specific to this component.

2023-04-03 17:56 UTC, Senait7-ux commented on packages/authentication/src/data/loginProvidersData.js
Over all i was thinking to have all related functions as well as data and components in a single package folder

2023-04-03 17:59 UTC, Senait7-ux commented on packages/authentication/src/data/graphQLQueries.js
the reason that I have named it graphQLQueries is maybe if other authentication related query to be included and exported in this specific package.

2023-04-03 19:17 UTC, Senait7-ux commented on packages/authentication/src/utils/env.js
I did not want to import the env from outside the shared  package folders based on my understanding of the component guideline documentation on Sharepoint.. Is it allowed to do so ?

documemtation: https://nih.sharepoint.com/:w:/r/sites/NCI-CBIIT-FNL-Bento/_layouts/15/Doc.aspx?sourcedoc=%7BB2AB7E52-3989-46B4-8F90-4B88A3BFBE7D%7D&file=Bento%20Component%20Guidelines.docx&action=default&mobileredirect=true

2023-04-03 19:20 UTC, Senait7-ux commented on packages/authentication/src/utils/getRedirectPath.js
the redirect is based on the query of redirect parameter of the provider authentication url

2023-04-03 19:35 UTC, Senait7-ux commented on packages/bento-frontend/src/components/Auth/AuthProvider.js
No it has not been removed, I just moved the signIn with google and NIH to the package and was planning to remove authProvider completely from the auth to the authentication package including the login component in the header.

2023-04-18 02:16 UTC, iksheth commented
Closing this PR as a new PR #778 has been created regarding the same changes with new structure.

2023-04-18 02:16 UTC, closed without merging