Bento 2340- Dar component completed
CBIIT/bento-frontend pull request #774
Opened 2023-04-12 21:20 UTC by Senait7-ux

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

2023-04-13 12:22 UTC, Senait7-ux commented
https://github.com/CBIIT/bento-frontend/pull/774

2023-04-17 16:50 UTC, iksheth requested changes

2023-04-17 16:53 UTC, Senait7-ux commented on packages/data-access-request/src/DataAccessRequest.js
> +import AlertMessage from '../../bento-frontend/src/bento-core/AlertMessage';
Okay, will pass it as a prop.

2023-04-17 18:22 UTC, Senait7-ux commented
https://github.com/CBIIT/bento-frontend/pull/774

2023-04-17 18:23 UTC, Senait7-ux commented on packages/data-access-request/src/DataAccessRequest.js
> +import AlertMessage from '../../bento-frontend/src/bento-core/AlertMessage';
https://github.com/CBIIT/bento-frontend/pull/774

2023-04-17 22:27 UTC, iksheth approved these changes

2023-04-17 22:28 UTC, iksheth commented
Looks good to me. Merging this PR & Deploying to DEV.

2023-04-17 22:28 UTC, merged