BENTO-2378 BENTO-2374
CBIIT/bento-frontend pull request #775
Opened 2023-04-13 16:33 UTC by rana22

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

2023-04-13 20:36 UTC, Senait7-ux commented
Defaulttabtheme.js  & Tabs.js

I think it would be better to have a way to create a generic and customizable header style instead of having it fixed like & .cases , & .sample and so on.

2023-04-13 20:37 UTC, Senait7-ux commented
Tabs.js
I think it would be better to have separate code related to css styling and components.

2023-04-14 12:41 UTC, rana22 commented
1. Moved the default style to separate file defaultTheme.js
2. We will used index for generic class name but there is also existing feature to add your custom class name (tester may required to have certain class name)

2023-04-17 22:22 UTC, iksheth requested changes

2023-04-17 22:22 UTC, iksheth commented on packages/tab/src/Tabs.js
> +//   /* tab headers and specific style generator */
Can we remove Un-used code?

2023-04-18 14:31 UTC, rana22 commented on packages/tab/src/Tabs.js
> +//   /* tab headers and specific style generator */
removed unused codes

2023-04-18 18:15 UTC, iksheth approved these changes

2023-04-18 18:16 UTC, merged